work_dir: "/mnt/md0/metapredict"
threads:
  normal: 6
  large: 6

# rasusa params (subsampling for speed)
rasusa:
  subsampling: TRUE
  coverage: 30
  genome_size: 2.4mb

use_porchop: TRUE
# nanofilt params
nanofilt:
  l: 500
  q: 10
  headcrop: 0
  tailcrop: 0

assembler_opts: --default # --default, --only-canu, --only-flye
# by default, canu and flye assemblies will be merged
# For single assembler i.e., canu and flye, # only polishment is applied.
# Skip quickmerge and circulator
# assembler params
flye:
  mode: --nano-raw

canu:
  size: 5m # estimated genomesize
  usegrid: False
  grid_opts: ''
  ex_args: 'cnsThreads=2 cnsMemory=32'


# quickmerge params (conseverative merge of lathe)
quickmerge:
  # choose assembly as query and ref for quickmerge
  ref_opts: flye # flye, canu
  # flye: flye assembly as query, canu as ref
  # canu: vice versa 
  ml: 10000
  c: 5
  hco: 10

# circlator params
circlator:
  assembler: canu
  data_type: nanopore-corrected
  bwa_opts: "'-x ont2d'" # escape single quotes
  merge_min_id: 85
  merge_breaklen: 1000

# minimap params
minimap:
  x: map-ont 

# racon params (lathe setting)
racon:
  iter: 2
  m: 8
  x: 6
  g: 8
  w: 500

# medaka params:
medaka:
  m: r941_min_fast_g507

