work_dir: "/mnt/md0/metapredict"
threads:
  normal: 6
  large: 6

# nanofilt params
nanofilt:
  l: 1000
  q: 10
  headcrop: 0
  tailcrop: 0
# assembler params
flye:
  mode: --nano-raw

canu:
  size: 20m # estimated genomesize
  usegrid: False
  grid_opts: ''
  ex_args: 'cnsThreads=2 cnsMemory=32'

# quickmerge params (conseverative merge of lathe)
quickmerge:
  ml: 10000
  c: 5
  hco: 10

# circlator params
circlator:
  assembler: canu
  data_type: nanopore-corrected
  bwa_opts: '-x ont2d'
  merge_min_id: 85
  merge_breaklen: 1000

# minimap params
minimap:
  x: map-ont 

# racon params (lathe setting)
racon:
  iter: 2
  m: 8
  x: 6
  g: 8
  w: 500

# medaka params:
medaka:
  m: r941_min_fast_g507

