work_dir: "/mnt/md0/metapredict"
threads:
  normal: 2
  large: 4

# nanofilt params
nanofilt:
  l: 1000
  q: 10
  headcrop: 50
  tialcrop: 50
# assembler params
flye:
  mode: --nano-raw

canu:
  size: 20m # estimated genomesize
  usegrid: False
  grid_opts: ''
  ex_args: 'cnsThreads=2 cnsMemory=32'

# quickmerge params (conseverative merge of lathe)
quickmerge:
  ml: 10000
  c: 5
  hco: 10