work_dir: "/mnt/md0/ontrapid"
database_dir: "/mnt/md0/Database/anvio"

threads:
  normal: 2
  large: 6

memory:
  normal_gb: 4 
  large_gb: 50

# rasusa params (subsampling for speed)
rasusa:
  subsampling: True
  coverage: 30
  genome_size: 2.4mb

use_porchop: False
# nanofilt params
nanofilt:
  l: 500
  q: 10
  headcrop: 0
  tailcrop: 0

assembler_opts: flye # default, canu, flye
# by default, canu and flye assemblies will be merged
# For single assembler i.e., canu and flye, # only polishment is applied.
# Skip quickmerge and circulator
# assembler params
flye:
  mode: --nano-raw
  ex_args: 

canu:
  size: 5m # estimated genomesize
  usegrid: False
  grid_opts: ''
  stopOnLowCoverage: 10
  minInputCoverage: 10
  ex_args: 'cnsThreads=2 cnsMemory=32'


# quickmerge params (conseverative merge of lathe)
quickmerge:
  # choose assembly as query and ref for quickmerge
  # select a folder containing "assembly.fasta"
  query: flye2polish
  ref: canu2polish
  # flye: flye assembly as query, canu as ref
  # canu: vice versa 
  ml: 10000
  c: 5
  hco: 10

# circlator params
circlator:
  assembler: spades
  data_type: nanopore-corrected
  bwa_opts: "'-x ont2d'" # escape single quotes
  merge_min_id: 85
  merge_breaklen: 1000

# minimap2 params
minimap2:
  x: map-ont 

# racon params (recommended by medaka)
racon:
  iter: 2
  m: 8
  x: -6
  g: -8
  w: 500

# medaka params:
medaka:
  iter: 1 
  m: r1041_e82_400bps_hac_v4.2.0
  cudnn: False

# assembly qc
busco:
  l: bacteria_odb10
  m: genome
  opts: ''

# pangenome
update_assembly: False
updated_assembly_dir: /mnt/md0/proferment/results/assembly_rename 
import_from_gbk: False # overide update_assembly
external_gbk_dir: /mnt/md0/proferment/results/gbk

# variants:
variants:
  ref: /mnt/md0/nano_snp/ref/ecoli_dh5a.fna #/mnt/md0/nano_snp/ref/ecoli_mg1655.fna
  medaka:
    model: r941_prom_hac_variant_g507
  clair:
    platform: ont
    model: r941_prom_sup_g506
    mode: --haploid_sensitive
  snpEff:
    g_version: Escherichia_coli_str_dh5a # Escherichia_coli_str_k_12_substr_mg1655
    chr_exist: "CP017100\\.1" # "U00096\\.3"
    chr_replace: Chromosome